version: '3'

services:
  web:
    build:
      context: .
    environment:
      - TZ=Canada/Eastern
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "todo_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/java/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
