version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
#    hostname: localhost
  #https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f
    environment:
      POSTGRES_USER: "todo_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/java/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
